---
- name: add repository
  ansible.builtin.import_tasks: repository.yml
  tags: repository
- name: install nodejs
  ansible.builtin.apt:
    name: nodejs
- name: install yarn
  community.general.npm:
    name: yarn
    global: true
