---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Add apt signing key
  ansible.builtin.get_url:
    url: "{{ nodejs_apt_key_url }}"
    dest: "{{ nodejs_apt_key_dest }}"
    mode: "0644"
- name: Add nodesource repository
  ansible.builtin.apt_repository:
    filename: nodesource
    repo: deb [signed-by={{ nodejs_apt_key_dest }}] https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_facts.distribution_release }} main
    state: present
