---
## @see https://github.com/nodesource/distributions
## @see https://deb.nodesource.com/setup_lts.x
- name: Install dependency packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Add apt signing key
  ansible.builtin.get_url:
    url: "{{ nodejs_apt_key_url }}"
    dest: "{{ nodejs_apt_key_download_dest }}"
    mode: "0644"
  register: nodejs_key_download_result
- name: Convert key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ nodejs_apt_key_dest }} {{ nodejs_apt_key_download_dest }}
  when: nodejs_key_download_result is changed
- name: Check architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  changed_when: false
  register: dpkg_result
- name: Set arch variables
  ansible.builtin.set_fact:
    nodejs_arch: "{{ dpkg_result.stdout }}"
- name: Add nodesource repository
  ansible.builtin.apt_repository:
    filename: nodesource
    repo: deb [arch={{ nodejs_arch }} signed-by={{ nodejs_apt_key_dest }}] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main
    state: present
- name: Add Nodejs apt Config
  ansible.builtin.copy:
    src: apt/preferences.d/nodejs
    dest: /etc/apt/preferences.d/nodejs
    mode: "0644"
