---
## @see https://github.com/nodesource/distributions
## @see https://deb.nodesource.com/setup_lts.x
- name: Install dependency packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3-apt
      - python3-debian
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Create GPG key directory
  ansible.builtin.file:
    path: "{{ nodejs_apt_key_dest | dirname }}"
    state: directory
    mode: "0755"
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ nodejs_apt_key_url }}"
    dest: "{{ nodejs_apt_key_download_dest }}"
    mode: "0644"
  register: nodejs_key_download_result
- name: Convert GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ nodejs_apt_key_dest }} {{ nodejs_apt_key_download_dest }}
  when: nodejs_key_download_result is changed
- name: Check architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  changed_when: false
  register: dpkg_result
- name: Set arch variables
  ansible.builtin.set_fact:
    nodejs_arch: "{{ dpkg_result.stdout }}"
- name: Add nodesource repository
  ansible.builtin.deb822_repository:
    name: nodesource
    uris: https://deb.nodesource.com/node_{{ nodejs_version }}.x
    suites: nodistro
    components: main
    architectures: "{{ nodejs_arch }}"
    signed_by: "{{ nodejs_apt_key_dest }}"
    enabled: true
    state: present
  register: apt_repository_result
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: apt_repository_result is changed
- name: Add Nodejs apt Config
  ansible.builtin.copy:
    src: apt/preferences.d/nodejs
    dest: /etc/apt/preferences.d/nodejs
    mode: "0644"
