---
- name: Verify
  hosts: all
  gather_facts: false
  check_mode: true
  become: true
  tasks:
    ## リポジトリのテスト
    - name: Check repository file
      ansible.builtin.stat:
        path: //etc/apt/sources.list.d/nodesource.sources
      register: nodesource_repo_result
    - name: Assert repository
      ansible.builtin.assert:
        that:
          - nodesource_repo_result.stat.exists
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nodejs']
          - ansible_facts.packages['nodejs'][0]['version'].startswith('22.')
    # npmコマンドのテスト
    - name: Check npm command
      ansible.builtin.stat:
        path: /usr/bin/npm
      register: npm_command_result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - npm_command_result.stat.exists
          - npm_command_result.stat.executable
    # yarnコマンドのテスト
    - name: Check yarn command
      ansible.builtin.stat:
        path: /usr/bin/yarn
      register: yarn_command_result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - yarn_command_result.stat.exists
          - yarn_command_result.stat.executable
    # pnpmコマンドのテスト
    - name: Check pnpm command
      ansible.builtin.stat:
        path: /usr/bin/pnpm
      register: pnpm_command_result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - pnpm_command_result.stat.exists
          - pnpm_command_result.stat.executable
