---
- name: Verify
  hosts: all
  gather_facts: false
  check_mode: true
  become: true
  tasks:
    - name: Check repository file
      ansible.builtin.stat:
        path: //etc/apt/sources.list.d/nodesource.list
      register: result
    - name: Assert repository
      ansible.builtin.assert:
        that:
          - result.stat.exists
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nodejs']
          - ansible_facts.packages['nodejs'][0]['version'].startswith('16.')
    # yarnのテスト
    - name: Check yarn command
      ansible.builtin.stat:
        path: /usr/bin/yarn
      register: result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - result.stat.exists
